const menu = [
  {
    id: 1,
    title: 'Jumbo',
    category: 'hatching',
    price: 170,
    img: require('../../assets/download (4).jpg'),
    desc: 'A 10 to 12 cm fish in the category of hatching.',
  },
  {
    id: 2,
    title: 'Post',
    category: 'hatching',
    price: 150,
    img: require('../../assets/download (3).jpg'),
    desc: 'A 9 to 10 cm fish in the category of hatching.',
  },
  {
    id: 3,
    title: 'Dry Organic Medication',
    category: 'medication',
    price: 5000,
    img: require('../../assets/images (2).jpg'),
    desc: 'For the treatment of hatchlings, sold at 5000/kg.',
  },
  {
    id: 4,
    title: 'Dry Fish (Small)',
    category: 'small fish',
    price: 20000,
    img: require('../../assets/images (4).jpg'),
    desc: 'Dry fish sold at 20000/kg.',
  },
  {
    id: 5,
    title: 'Dry Fish (Big)',
    category: 'big fish',
    price: 25000,
    img: require('../../assets/images (4).jpg'),
    desc: 'Dry fish in the big fish category, sold at 25000/kg.',
  },
  {
    id: 6,
    title: 'Larvae',
    category: 'black soldier fly',
    price: 2000,
    img: require('../../assets/images.jpg'),
    desc: 'Sold at 2000/kg in the black soldier fly category.',
  },
  {
    id: 7,
    title: 'Pupal Larvae',
    category: 'black soldier fly',
    price: 18000,
    img: require('../../assets/images (1).jpg'),
    desc: 'Sold at 18000/kg in the black soldier fly category.',
  },
  {
    id: 8,
    title: 'Table Size',
    category: 'big fish',
    price: 4200,
    img: require('../../assets/india-929719_1280.jpg'),
    desc: 'Weighing 1kg and above, sold at 4200/kg.',
  },
  {
    id: 9,
    title: 'LoveNet',
    category: 'black soldier fly',
    price: 15000,
    img: require('../../assets/images (3).jpg'),
    desc: 'A product in the black soldier fly category, priced at 15000.',
  },
  {
    id: 10,
    title: 'Organic Manure',
    category: 'black soldier fly',
    price: 2000,
    img: require('../../assets/top-view-basket-veggies-with-copy-space.jpg'),
    desc: 'Sold at 2000/kg in the black soldier fly category.',
  },
  {
    id: 11,
    title: 'Alkalizer',
    category: 'water treatment',
    price: 100000,
    img: require('../../assets/images (5).jpg'),
    desc: 'treatment of water PH',
  },
];

export default menu;
